"""added user_uid as foreign key to books

Revision ID: 7a09ed731649
Revises: 19442f1df6c4
Create Date: 2025-03-13 09:02:58.844473

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a09ed731649"
down_revision: Union[str, None] = "19442f1df6c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "user_uid")
    # ### end Alembic commands ###
